-- =============================================================================
-- Enable weapon mastery for the remaining 10 guns (badge art uploaded to
-- Cloudinary laseropsmalta.com/mastery-badges). After this, every visible gun
-- has mastery and "Mastery coming soon" no longer appears.
-- =============================================================================
insert into public.weapon_mastery (gun_name, enabled, sort_order, bronze_badge_url, silver_badge_url, gold_badge_url, platinum_badge_url)
values
  ('Colt M4A3 Centurion', true, 9, 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493200/laseropsmalta.com/mastery-badges/Colt_M4A3_Centurion_Bronze.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493203/laseropsmalta.com/mastery-badges/Colt_M4A3_Centurion_Silver.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493201/laseropsmalta.com/mastery-badges/Colt_M4A3_Centurion_Gold.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493202/laseropsmalta.com/mastery-badges/Colt_M4A3_Centurion_Platinum.png'),
  ('HK416 Bergman', true, 10, 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493203/laseropsmalta.com/mastery-badges/HK416_Bergman_Bronze.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493206/laseropsmalta.com/mastery-badges/HK416_Bergman_Silver.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493204/laseropsmalta.com/mastery-badges/HK416_Bergman_Gold.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493205/laseropsmalta.com/mastery-badges/HK416_Bergman_Platinum.png'),
  ('ARP 556 Snowstorm', true, 11, 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493196/laseropsmalta.com/mastery-badges/ARP_Snowstorm_Bronze.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493199/laseropsmalta.com/mastery-badges/ARP_Snowstorm_Silver.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493197/laseropsmalta.com/mastery-badges/ARP_Snowstorm_Gold.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493198/laseropsmalta.com/mastery-badges/ARP_Snowstorm_Platinum.png'),
  ('Akm Legend', true, 12, 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493189/laseropsmalta.com/mastery-badges/AKM_Legend_Bronze.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493191/laseropsmalta.com/mastery-badges/AKM_Legend_Silver.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493190/laseropsmalta.com/mastery-badges/AKM_Legend_Gold.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493191/laseropsmalta.com/mastery-badges/AKM_Legend_Platinum.png'),
  ('AKS-74U Falcon', true, 13, 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493192/laseropsmalta.com/mastery-badges/AKS74U_Falcon_Bronze.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493195/laseropsmalta.com/mastery-badges/AKS74U_Falcon_Silver.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493193/laseropsmalta.com/mastery-badges/AKS74U_Falcon_Gold.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493194/laseropsmalta.com/mastery-badges/AKS74U_Falcon_Platinum.png'),
  ('AK-12 Serval', true, 14, 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493186/laseropsmalta.com/mastery-badges/AK12_Serval_Bronze.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493188/laseropsmalta.com/mastery-badges/AK12_Serval_Silver.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493187/laseropsmalta.com/mastery-badges/AK12_Serval_Gold.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493187/laseropsmalta.com/mastery-badges/AK12_Serval_Platinum.png'),
  ('P-90 Kayman', true, 15, 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493213/laseropsmalta.com/mastery-badges/P90_Kayman_Bronze.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493216/laseropsmalta.com/mastery-badges/P90_Kayman_Silver.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493214/laseropsmalta.com/mastery-badges/P90_Kayman_Gold.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493215/laseropsmalta.com/mastery-badges/P90_Kayman_Platinum.png'),
  ('MP-5 Wolf', true, 16, 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493209/laseropsmalta.com/mastery-badges/MP5_Wolf_Bronze.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493213/laseropsmalta.com/mastery-badges/MP5_Wolf_Silver.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493210/laseropsmalta.com/mastery-badges/MP5_Wolf_Gold.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493212/laseropsmalta.com/mastery-badges/MP5_Wolf_Platinum.png'),
  ('KEDR', true, 17, 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493206/laseropsmalta.com/mastery-badges/KEDR_Bronze.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493209/laseropsmalta.com/mastery-badges/KEDR_Silver.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493207/laseropsmalta.com/mastery-badges/KEDR_Gold.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493208/laseropsmalta.com/mastery-badges/KEDR_Platinum.png'),
  ('Steyr Aug 3 Cobra', true, 18, 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493216/laseropsmalta.com/mastery-badges/Steyr_AUG3_Cobra_Bronze.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493218/laseropsmalta.com/mastery-badges/Steyr_AUG3_Cobra_Silver.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493217/laseropsmalta.com/mastery-badges/Steyr_AUG3_Cobra_Gold.png', 'https://res.cloudinary.com/dqud5b7pa/image/upload/v1791493218/laseropsmalta.com/mastery-badges/Steyr_AUG3_Cobra_Platinum.png')
on conflict (operator_id, gun_name) do update set
  enabled            = excluded.enabled,
  sort_order         = excluded.sort_order,
  bronze_badge_url   = excluded.bronze_badge_url,
  silver_badge_url   = excluded.silver_badge_url,
  gold_badge_url     = excluded.gold_badge_url,
  platinum_badge_url = excluded.platinum_badge_url,
  updated_at         = now();
